bookproject/bookapp/urls.py
from django.urls import path
from . import views
app_name='bookapp'
urlpatterns = [

    path('',views.index,name='index'),
    path('book/<int:book_id>/',views.detail,name='detail'),
    path('add/',views.add_book,name='add_book'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')


]

bookproject/bookproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("bookapp.urls"))

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

bookproject/bookapp/models.py
from django.db import models

# Create your models here.
class Book(models.Model):
    name=models.CharField(max_length=50)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')
    def __str__(self):
        return self.name

bookproject/bookapp/forms.py
from django import forms
from .models import Book
class BookForm(forms.ModelForm):
    class Meta:
        model=Book
        fields=['name','desc','year','img']

bookproject/bookapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

# Create your views here.
from bookapp.forms import BookForm
from bookapp.models import Book


def index(request):
    book=Book.objects.all()
    context={
        'book_list':book
    }
    return render(request,'index.html',context)
def detail(request,book_id):
    book=Book.objects.get(id=book_id)
    return render(request,"detail.html",{'book':book})
def add_book(request):
    if request.method=="POST":
        name=request.POST.get('name',)
        desc=request.POST.get('desc',)
        year=request.POST.get('year',)
        img=request.FILES['img']
        book=Book(name=name,desc=desc,year=year,img=img)
        book.save()
    return render(request,'add.html')
def update(request,id):
    book=Book.objects.get(id=id)
    form=BookForm(request.POST or None,request.FILES,instance=book)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'book':book})
def delete(request,id):
    if request.method=='POST':
        book=Book.objects.get(id=id)
        book.delete()
        return redirect('/')
    return render(request,'delete.html')

bookproject/bookapp/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <input type="text" name="name" placeholder="Enter Book Name"><br>
  <input type="text" name="desc" placeholder="Enter Description"><br>
  <input type="text" name="year" placeholder="Enter Published Year"><br>
  <input type="file" name="img"><br>
  <input type="submit">
</form>
{% endblock %}

bookproject/bookapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>booklist</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>

<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
      Online Book Store
  </a>

</nav>
 {% block body %}
{% endblock %}
</body>
</html>

bookproject/bookapp/templates/delete.html
<form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete ?</p>
    <input type="submit" value="Delete">
</form>

bookproject/bookapp/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
        <img src="{{book.img.url}}" width="350" height="400">
    </div>
    <div class="col-md-6">
        <b><h2>{{book.name}}</b></h2>
        <h6>{{book.desc}}</h6>
        <h6>{{book.year}}</h6>
        <a class="btn btn-warning" href="{% url 'bookapp:update' book.id %}">Update</a>
        <a class="btn btn-danger" href="{% url 'bookapp:delete' book.id %}">Delete</a>
        </div>
    </div>
</div>
{% endblock %}

bookproject/bookapp/templates/edit.html
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit">
</form>

bookproject/bookapp/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        {% for i in book_list %}
        <div class="col-md-3">
        <div class="card-deck">
            <div class="card text-center">
          <div class="card" style="width: 18rem;margin: 1.5rem">
              <img class="card-img-top" src="{{i.img.url}}" alt="" height="390" width="300">
            <div class="card-body">
            <h5 class="card-title">{{i.name}}</h5>
    <a href="{% url 'bookapp:detail' i.id %}" class="btn btn-primary">View details</a>
  </div>
</div>
            </div>
        </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}